port: 7880
environment: dev
bind_addresses:
  - "0.0.0.0"
rtc:
  tcp_port: 7881
  port_range_start: 50100
  port_range_end: 50200
  use_external_ip: false
redis:
    address: 127.0.0.1:6379
    username: ""
    password: ""
    db: 1
turn:
  enabled: false
  # domain: turn.3dns.eu
  # cert_file: ""
  # key_file: ""
  # tls_port: 5349
  # udp_port: 5349
  # external_tls: true
keys:
  prod: "**************************************"
signal_relay:
  enabled: true
